# Copyright IBM Corporation 2018.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image:
  repository: ibmcom/txseries
  tag: latest 
  pullPolicy: IfNotPresent

admin_service:
  type: NodePort
  name: TXAdminConsole
  port: 9443 
  targetPort: 9443 

listener_service:
  type: NodePort
  name: IPIC-Service 
  port: 1435
  targetPort: 1435

###############################################################################
## Persistence Storage
###############################################################################

## Persistence is disabled by default, set Enabled: true to use
persistence:
  enablePercistency: true
  useDynamicProvisioning: true
  name: "txseries-pvc"
  ## Tranlog requires a Persistence Storage volume size minimum of 1Gi
  size: "1Gi"
  # if your not using dynamic provisioning, you can use selectors to 
  # refine the binding process. You cannot specify a selector if your using dynamic provisioning!
  selector:
    label: ""
    value: ""
  ## Specify the name of the StorageClass
  ## Setting StorageClass: "" will use whatever storageClass is currently
  ## setup as the Default
  storageClassName: "" 

###############################################################################
## Auto scaling
###############################################################################
replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  
###############################################################################
## Resource constraints
###############################################################################
resources:
  constraints: 
    enabled: false
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi
